//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.trkcrs = new HashSet<trkcr>();
        }
    
        public int crsuniq { get; set; }
        public string coursec { get; set; }
        public string descript { get; set; }
        public string crscats { get; set; }
        public string deptc { get; set; }
        public Nullable<decimal> sectsize { get; set; }
        public Nullable<decimal> tasize { get; set; }
        public string crsstatc { get; set; }
        public Nullable<decimal> trmdur { get; set; }
        public Nullable<decimal> perdur { get; set; }
        public Nullable<decimal> lograden { get; set; }
        public Nullable<decimal> higraden { get; set; }
        public string altc { get; set; }
        public string genderenrl { get; set; }
        public Nullable<decimal> isschedule { get; set; }
        public Nullable<decimal> takeattnd { get; set; }
        public Nullable<decimal> countattnd { get; set; }
        public Nullable<decimal> conflictok { get; set; }
        public Nullable<decimal> flag1 { get; set; }
        public Nullable<decimal> flag2 { get; set; }
        public Nullable<decimal> asgngrades { get; set; }
        public Nullable<decimal> posttohist { get; set; }
        public Nullable<decimal> varcr { get; set; }
        public string crsnotes { get; set; }
        public Nullable<decimal> snreserve1 { get; set; }
        public Nullable<decimal> snreserve2 { get; set; }
        public Nullable<int> CoreID { get; set; }
    
        public virtual ICollection<trkcr> trkcrs { get; set; }
    }
}
