//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facstat
    {
        public facstat()
        {
            this.facdemoes = new HashSet<facdemo>();
        }
    
        public int facuniq { get; set; }
        public string ident { get; set; }
        public int funiq { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<System.DateTime> xdate { get; set; }
        public Nullable<System.DateTime> evaldate { get; set; }
        public Nullable<decimal> fte { get; set; }
        public Nullable<int> trkuniq { get; set; }
        public string facstatc { get; set; }
        public Nullable<decimal> dbadmin { get; set; }
        public Nullable<decimal> siteadmin { get; set; }
        public Nullable<decimal> counsel { get; set; }
        public Nullable<decimal> teacher { get; set; }
        public Nullable<decimal> certif { get; set; }
        public string jobc { get; set; }
        public string sprvisec { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgdt { get; set; }
        public Nullable<decimal> snreserve1 { get; set; }
        public Nullable<decimal> snreserve2 { get; set; }
    
        public virtual ICollection<facdemo> facdemoes { get; set; }
        public virtual facdemo facdemo { get; set; }
        public virtual track track { get; set; }
    }
}
