//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstmeet
    {
        public mstmeet()
        {
            this.stuscheds = new HashSet<stusched>();
        }
    
        public int meetuniq { get; set; }
        public Nullable<int> mstuniq { get; set; }
        public string termc { get; set; }
        public Nullable<decimal> cycldayn { get; set; }
        public Nullable<decimal> periodn { get; set; }
        public string classroom { get; set; }
        public Nullable<decimal> takeattnd { get; set; }
        public Nullable<decimal> countattnd { get; set; }
        public Nullable<decimal> ishomeroom { get; set; }
        public Nullable<decimal> scanattnd { get; set; }
        public Nullable<decimal> snreserve1 { get; set; }
        public Nullable<decimal> snreserve2 { get; set; }
    
        public virtual mstsched mstsched { get; set; }
        public virtual ICollection<stusched> stuscheds { get; set; }
    }
}
