//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class school
    {
        public int schuniq { get; set; }
        public string schoolc { get; set; }
        public string schname { get; set; }
        public string addr { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string schdistc { get; set; }
        public string building { get; set; }
        public string phnnumber { get; set; }
        public Nullable<decimal> egraden { get; set; }
        public Nullable<decimal> xgraden { get; set; }
        public Nullable<decimal> pgraden { get; set; }
        public string schtypec { get; set; }
        public Nullable<decimal> chksum { get; set; }
        public string modkey { get; set; }
        public Nullable<decimal> isdo { get; set; }
        public decimal schyear { get; set; }
        public string seschoolc { get; set; }
        public Nullable<int> snsrvuniq { get; set; }
        public string principal { get; set; }
        public Nullable<decimal> monattend { get; set; }
        public string url { get; set; }
        public string emailaddr { get; set; }
        public string maintrackc { get; set; }
        public Nullable<decimal> nyinit { get; set; }
        public Nullable<decimal> rnyrend { get; set; }
        public bool RetainLockers { get; set; }
        public bool RetainAdvisors { get; set; }
        public bool ExcludeFromClearinghouse { get; set; }
        public string ShortName { get; set; }
        public string UrlToken { get; set; }
    }
}
