//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SJSDDBEntities : DbContext
    {
        public SJSDDBEntities()
            : base("name=SJSDDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<course> courses { get; set; }
        public DbSet<facdemo> facdemoes { get; set; }
        public DbSet<facstat> facstats { get; set; }
        public DbSet<school> schools { get; set; }
        public DbSet<studemo> studemoes { get; set; }
        public DbSet<stusched> stuscheds { get; set; }
        public DbSet<track> tracks { get; set; }
        public DbSet<trkcr> trkcrs { get; set; }
        public DbSet<mstmeet> mstmeets { get; set; }
        public DbSet<mstsched> mstscheds { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
