//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stusched
    {
        public int scduniq { get; set; }
        public int suniq { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string escdchgyc { get; set; }
        public Nullable<System.DateTime> xdate { get; set; }
        public string xscdchgyc { get; set; }
        public string scdstatc { get; set; }
        public Nullable<int> requniq { get; set; }
        public int meetuniq { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgdt { get; set; }
        public Nullable<decimal> snreserve1 { get; set; }
        public Nullable<decimal> snreserve2 { get; set; }
        public Nullable<decimal> ista { get; set; }
        public Nullable<decimal> elocked { get; set; }
        public Nullable<decimal> xlocked { get; set; }
        public int notconcurrent { get; set; }
    
        public virtual studemo studemo { get; set; }
        public virtual mstmeet mstmeet { get; set; }
    }
}
