//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        public track()
        {
            this.facstats = new HashSet<facstat>();
            this.trkcrs = new HashSet<trkcr>();
        }
    
        public int trkuniq { get; set; }
        public string trackc { get; set; }
        public string descript { get; set; }
        public string schoolc { get; set; }
        public decimal schyear { get; set; }
        public decimal ppd { get; set; }
        public decimal dpc { get; set; }
        public decimal tpy { get; set; }
        public Nullable<decimal> mpy { get; set; }
        public Nullable<decimal> perqtr { get; set; }
        public Nullable<decimal> perhalf { get; set; }
        public Nullable<decimal> perfull { get; set; }
        public Nullable<decimal> countabs { get; set; }
        public Nullable<decimal> posatt { get; set; }
        public Nullable<decimal> mpfte { get; set; }
        public Nullable<decimal> usesat { get; set; }
        public Nullable<int> belluniq { get; set; }
        public Nullable<decimal> skipdays { get; set; }
        public Nullable<decimal> credyr { get; set; }
        public Nullable<decimal> sched { get; set; }
    
        public virtual ICollection<facstat> facstats { get; set; }
        public virtual ICollection<trkcr> trkcrs { get; set; }
    }
}
