//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trkcr
    {
        public trkcr()
        {
            this.mstscheds = new HashSet<mstsched>();
        }
    
        public int trkcrsuniq { get; set; }
        public int trkuniq { get; set; }
        public Nullable<int> crsuniq { get; set; }
        public Nullable<decimal> numsect { get; set; }
        public Nullable<decimal> ppc { get; set; }
        public Nullable<decimal> eperiodn { get; set; }
        public Nullable<decimal> lperiodn { get; set; }
        public string termc { get; set; }
        public Nullable<decimal> snreserve1 { get; set; }
        public Nullable<decimal> snreserve2 { get; set; }
        public Nullable<decimal> gradcr { get; set; }
        public Nullable<decimal> sectsize { get; set; }
        public Nullable<decimal> tasize { get; set; }
        public string marksetc { get; set; }
        public Nullable<decimal> lograden { get; set; }
        public Nullable<decimal> higraden { get; set; }
    
        public virtual course course { get; set; }
        public virtual track track { get; set; }
        public virtual ICollection<mstsched> mstscheds { get; set; }
    }
}
