//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasCourseCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public Nullable<int> funiq { get; set; }
        public Nullable<int> suniq { get; set; }
        public Nullable<int> conuniq { get; set; }
        public bool CanSelectDatabase { get; set; }
        public bool CanImpersonate { get; set; }
        public string LastImpersonateUserName { get; set; }
        public string Password { get; set; }
        public byte[] PasswordSalt { get; set; }
        public byte[] PasswordHash { get; set; }
        public string TemporaryPassword { get; set; }
        public byte[] TemporaryPasswordSalt { get; set; }
        public byte[] TemporaryPasswordHash { get; set; }
        public bool MustChangePassword { get; set; }
        public short LoginAttempts { get; set; }
        public Nullable<System.DateTime> LockedUntil { get; set; }
        public string LockedReason { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<int> LastUserSessionID { get; set; }
        public Nullable<int> LastImpersonateSessionID { get; set; }
        public System.Guid UserGUID { get; set; }
    
        public virtual facdemo facdemo { get; set; }
        public virtual studemo studemo { get; set; }
    }
}
